version: '3.8'
services:
  app:
    env_file: .env
    build: .
    # command: sequelize-auto -o "./models" -d ${DATABASE_NAME} -h ${DATABASE_URL} -u ${DATABASE_USER} -p ${DATABASE_PORT} -x ${DATABASE_PASS} -e ${DATABASE_CONNECTION}
    volumes:
      - .:/app
    ports:
      - 3000:3000
   
  